fedavg_blades:
  run: FEDPROX
  stop:
    training_iteration: 2000

  config:
    random_seed:
      grid_search: [ 121 ]
    dataset_config:
      type: CIFAR10
      num_clients: 10
      num_classes: 10
      train_batch_size: 64

      partitioner_config:
        type: DirichletPartitioner
        alpha:
          grid_search: [200, 0.1]
        num_clients: 10

    evaluation_interval: 50

    num_remote_workers: 0
    num_gpus_per_worker: 0.5
    num_cpus_per_worker: 0
    num_cpus_for_driver: 4
    num_gpus_for_driver: 0.5

    global_model: resnet

    client_config:
      lr: 1.0
      momentum:
        grid_search: [ 0.0 ]

    server_config:
      aggregator:
        grid_search: [
          type: Mean
        ]

      optimizer:
        type: SGD
        lr: 0.1
        lr_schedule: [ [ 0, 0.1 ], [ 1500, 0.1 ], [ 1501, 0.01 ], [ 2000, 0.01 ] ]
        momentum:
          grid_search: [ 0.0 ]
