fedavg_blades:
  run: FEDAVG
  stop:
    training_iteration: 100
    # train_loss: 100

  config:
    random_seed:
      grid_search: [111]
    dataset_config:
      type: CIFAR10
      num_clients: 60
      num_classes: 10
      train_batch_size: 64

      partitioner_config:
        type: DirichletPartitioner
        alpha: 
          grid_search: [0.1]
        num_clients: 60

    evaluation_interval: 50

    num_remote_workers: 2
    num_gpus_per_worker: 0.5
    num_cpus_per_worker: 2
    num_cpus_for_driver: 4
    num_gpus_for_driver: 0.5

    # num_remote_workers: 14
    # num_gpus_per_worker: 0.25
    # num_cpus_per_worker: 2
    # num_cpus_for_driver: 2
    # num_gpus_for_driver: 0.5

    # num_clients: 2
    # global_model:
      # grid_search: [cct]
    # global_model: cct
    global_model: resnet

    client_config:
        lr: 0.1
        num_batch_per_round: 20
        momentum:
          grid_search: [0.0]

    server_config:
      aggregator: 
        type: Mean
        
      optimizer:
        type: SGD
        lr: 1.0
        # lr_schedule: [[0, 0.1], [1500, 0.1], [1501, 0.01], [2000, 0.01]]
        # lr: 0.1
        # lr_schedule: [[0, 0.1], [1500, 0.1],  [1501, 0.05], [3000, 0.05], [3001, 0.005], [4000, 0.005]]
        momentum:
          # grid_search: [0.0]
          grid_search: [0.0]
