fedavg_blades:
  run: FEDAVG
  stop:
    training_iteration: 2000

  config:
    random_seed:
      grid_search: [ 121 ]
    dataset_config:
      type: CIFAR10
      num_clients: 60
      num_classes: 10
      train_batch_size: 64

      splitter_config:
        type: IIDSplitter
        # alpha: 100.
        num_clients: 60

    evaluation_interval: 50

    num_remote_workers: 0
    num_gpus_per_worker: 0.5
    num_cpus_per_worker: 0
    num_cpus_for_driver: 4
    num_gpus_for_driver: 0.5

    global_model: resnet

    client_config:
      lr: 1.0
      momentum:
        grid_search: [ 0.0 ]

      # callbacks_config:
      #   type: blades.clients.callbacks.ClippingCallback
      #   clip_threshold:
      #     grid_search: [5.0]

    server_config:
      aggregator:
        grid_search: [
          # type: Mean,
          # type: Clippedclustering,
          # type: Median,
          # type: GeoMed,
          type: DnC,
          # type: Trimmedmean,
          # type: Signguard,
          # type: Multikrum,
          # type: Centeredclipping
        ]

      optimizer:
        type: SGD
        lr: 0.1
        lr_schedule: [ [ 0, 0.1 ], [ 1500, 0.1 ], [ 1501, 0.01 ], [ 2000, 0.01 ] ]
        momentum:
          grid_search: [ 0.0 ]

    num_malicious_clients:
      # grid_search:  [3]
      grid_search: [ 6, 9 ]
      # grid_search:  [3, 6, 9, 12, 15, 18]

    adversary_config:
      grid_search:
        - type: blades.adversaries.ALIEAdversary
        - type: blades.adversaries.LabelFlipAdversary
        - type: blades.adversaries.NoiseAdversary
        - type: blades.adversaries.SignFlipAdversary
        - type: blades.adversaries.IPMAdversary
          scale: 0.1
        - type: blades.adversaries.IPMAdversary
          scale: 100
        - type: blades.adversaries.MinMaxAdversary
